title: GitHub CLI
description: TODO
markdown: kramdown
twitter:
  username: github

plugins:
  - jekyll-feed
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - bin
  - vendor
  - node_modules
