title: GitHub CLI
description: TODO
cli-latest-version: 0.4.0

twitter:
  username: github

plugins:
  - jekyll-feed
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - Gemfile
  - Gemfile.lock
  - Brewfile
  - README.md
  - bin
  - script
  - vendor
  - node_modules
  - package.json
  - package-lock.json
